(()=>{
'use strict';
const D=Drill,app=document.getElementById('app');let state=D.initial(),screen='home',entry='',frame=null,advance=null,notice='',customDraft=null;
try{state=D.hydrate(JSON.parse(localStorage.getItem(D.KEY)));}catch(_){}
const now=()=>performance.now();
function save(){try{const snap=JSON.parse(JSON.stringify(state));if(snap.active?.phase==='running')snap.active.remaining=D.remaining(state.active,now());localStorage.setItem(D.KEY,JSON.stringify(snap));}catch(_){notice='Not saved';}}
function stop(){cancelAnimationFrame(frame);clearTimeout(advance);frame=null;advance=null;}
function button(text,action,cls='',attrs=''){return `<button class="${cls}" data-action="${action}" ${attrs}>${text}</button>`;}
function render(){stop();document.getElementById('home').hidden=screen==='home';if(screen==='home')home();else if(state.active?.phase==='complete')complete();else if(state.active)play();else{screen='home';home();}}
function home(){const s=state.settings,r=state.active,canResume=r&&r.phase!=='complete',custom=s.count==='custom';app.innerHTML=`<section class="setup"><div><span class="label">Math</span><div class="choices" role="group" aria-label="Operation">${D.OPS.map(op=>button(op,`op:${op}`,s.op===op?'selected':'',`aria-label="${op==='+'?'Addition':op==='×'?'Multiplication':'Division'}" aria-pressed="${s.op===op}"`)).join('')}</div></div><div><span class="label">Time</span><div class="choices time" role="group" aria-label="Seconds per question">${D.DURATIONS.map(sec=>button(`${sec}s`,`seconds:${sec}`,s.seconds===sec?'selected':'',`aria-pressed="${s.seconds===sec}"`)).join('')}</div></div>${s.op==='+'?`<div class="difficulty"><span class="label">Level</span><div class="choices levels" role="group" aria-label="Addition difficulty">${D.LEVELS.map(level=>button(`${level[0].toUpperCase()+level.slice(1)}<small>≤ ${level==='easy'?10:level==='medium'?20:s.difficultLimit}</small>`,`level:${level}`,s.difficulty===level?'selected':'',`aria-label="${level[0].toUpperCase()+level.slice(1)}" aria-pressed="${s.difficulty===level}"`)).join('')}</div>${s.difficulty==='difficult'?`<div class="limit-row"><label for="sumLimit">Sum ≤</label><select id="sumLimit" aria-label="Difficult sum limit">${[30,40,50,60,70,80,90,100].map(n=>`<option value="${n}" ${s.difficultLimit===n?'selected':''}>${n}</option>`).join('')}</select></div>`:''}</div>`:''}<div class="count-section"><span class="label">Questions</span><div class="choices counts" role="group" aria-label="Round length">${[10,15,20,'custom','unlimited'].map(n=>button(n==='custom'?'Custom':n==='unlimited'?'∞':n,`count:${n}`,s.count===n?'selected':'',`aria-label="${n==='unlimited'?'Unlimited':n==='custom'?'Custom':n+' questions'}" aria-pressed="${s.count===n}"`)).join('')}</div>${custom?`<div class="custom-row"><input id="customCount" type="text" inputmode="numeric" autocomplete="off" maxlength="4" aria-label="Custom question count"><span>1–999</span></div>`:''}</div><div class="start-buttons">${canResume?button('Resume','continue','soft'):r?.phase==='complete'?button('Results','continue','soft'):''}${button('Start','start','primary')}</div>${notice?`<div class="small-info" role="alert">${notice}</div>`:''}</section>`;if(custom){const input=document.getElementById('customCount');input.value=customDraft??String(s.customCount);input.addEventListener('input',()=>{customDraft=input.value;notice='';});}const limit=document.getElementById('sumLimit');if(limit)limit.addEventListener('change',()=>{s.difficultLimit=Number(limit.value);save();render();});}
function play(){const r=state.active,p=D.record(r).problem,paused=r.phase==='paused',feedback=r.phase==='feedback',result=D.record(r).result;
app.innerHTML=`<section class="game ${feedback?'feedback':''}"><div class="game-bar"><span class="counter">${r.index+1} / ${r.unlimited?'∞':r.records.length}</span><span class="badge">${r.op} · ${r.seconds}s</span>${r.unlimited?button('Finish','finish','finish soft'):''}${button(paused?'Resume':'Pause',paused?'resume':'pause','pause soft',feedback?'disabled':'')}</div><div class="question" aria-live="polite">${paused?`<div class="paused-label">Paused</div>${button('Resume','resume','primary')}`:feedback?`<div class="result ${result.status==='correct'?'':'wrong'}">${result.status==='correct'?'✓':result.status==='timeout'?'Time':'Try again'}</div><div class="answer-line">${p.a} ${p.op} ${p.b} = ${p.answer}</div>`:`<div class="timer-track" role="progressbar" aria-label="Time remaining" aria-valuemin="0" aria-valuemax="${r.seconds}"><div id="timerFill" class="timer-fill"></div></div><span id="timerLabel" class="timer-label">${(D.remaining(r,now())/1000).toFixed(1)}s</span><div class="expression">${p.a} ${p.op} ${p.b} =</div><div id="answer" class="answer" role="status" aria-label="Answer">${entry||'?'}</div><div id="notice" class="toast">${notice}</div>`}</div><div class="pad" role="group" aria-label="Answer keypad">${[1,2,3,4,5,6,7,8,9,'⌫',0,'✓'].map(x=>button(x,`key:${x}`,x==='✓'?'primary action':x==='⌫'?'soft action':'',`${paused||feedback?'disabled':''} ${x==='✓'?'aria-label="Check answer"':x==='⌫'?'aria-label="Delete"':`aria-label="${x}"`}`)).join('')}</div></section>`;
if(r.phase==='ready'){const id=r.id,index=r.index;frame=requestAnimationFrame(()=>{if(screen!=='play'||document.hidden||state.active?.id!==id||r.index!==index)return;if(D.begin(r,now())){save();tick();}});}else if(r.phase==='running')tick();else if(feedback){const id=r.id,index=r.index;advance=setTimeout(()=>{if(screen!=='play'||document.hidden||state.active?.id!==id||r.index!==index)return;D.next(state);entry='';notice='';save();render();},result.status==='correct'?500:1100);}}
function tick(){const r=state.active;if(screen!=='play'||!r||r.phase!=='running')return;const ms=D.remaining(r,now());if(ms<=0){D.grade(r,entry,now(),r.index);save();render();return;}const fill=document.getElementById('timerFill'),label=document.getElementById('timerLabel');if(fill){fill.style.transform=`scaleX(${ms/(r.seconds*1000)})`;fill.classList.toggle('urgent',ms<1000);fill.parentElement.setAttribute('aria-valuenow',(ms/1000).toFixed(1));}if(label)label.textContent=`${(ms/1000).toFixed(1)}s`;frame=requestAnimationFrame(tick);}
function complete(){const r=state.active,m=D.summary(r),wrong=r.records.filter(x=>x.result&&x.result.status!=='correct');app.innerHTML=`<section class="summary"><span class="label">${r.op} · ${r.seconds}s${r.op==='+'?` · ≤ ${r.sumLimit}`:''}</span>${m.master?'<div class="master">Master! ✦</div>':''}<div class="summary-score">${m.correct}<small> / ${m.total}</small></div><div class="summary-actions">${wrong.length?button('Practice mistakes','retry','soft'):''}${button('New round','start','primary')}</div>${wrong.length?`<div class="notes"><span class="label">Wrong answers · ${wrong.length}</span>${wrong.map(x=>`<div class="note-row"><strong>${x.problem.a} ${x.problem.op} ${x.problem.b}</strong><span><b class="miss">${x.result.status==='timeout'?'Time':x.result.answer}</b><span class="note-arrow">→</span><b class="correct">${x.problem.answer}</b></span></div>`).join('')}</div>`:''}${button('Math & time','home','soft')}</section>`;}
function pause(){const r=state.active;if(r?.phase==='running'){D.pause(r,now());save();}else if(r?.phase==='ready'){r.phase='paused';save();}}
function submit(){const r=state.active;if(!r)return;const out=D.grade(r,entry,now(),r.index);if(out.invalid){notice='?';document.getElementById('notice').textContent=notice;return;}if(out.ignored)return;save();notice='';render();}
app.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b||b.disabled)return;const a=b.dataset.action;if(a.startsWith('op:')){state.settings.op=a.slice(3);save();render();}else if(a.startsWith('seconds:')){state.settings.seconds=Number(a.slice(8));save();render();}else if(a.startsWith('level:')){state.settings.difficulty=a.slice(6);notice='';save();render();}else if(a.startsWith('count:')){const value=a.slice(6);state.settings.count=['custom','unlimited'].includes(value)?value:Number(value);notice='';save();render();}else if(a==='start'){if(state.settings.count==='custom'){const value=D.customCount(customDraft??state.settings.customCount);if(value===null){notice='1–999';return render();}state.settings.customCount=value;}if(!D.start(state))return;screen='play';entry='';notice='';save();render();}else if(a==='continue'){screen='play';entry='';notice='';render();}else if(a==='resume'){if(D.resume(state.active,now())){screen='play';entry='';notice='';save();render();}}else if(a==='pause'){pause();render();}else if(a==='home'){pause();screen='home';render();}else if(a==='finish'){if(D.finish(state,now(),entry)){entry='';notice='';save();render();}}else if(a==='retry'){if(D.retry(state)){screen='play';entry='';notice='';save();render();}}else if(a.startsWith('key:')){if(state.active?.phase!=='running')return;const key=a.slice(4);if(key==='✓')return submit();if(D.remaining(state.active,now())<=0){D.grade(state.active,entry,now());save();return render();}if(key==='⌫')entry=entry.slice(0,-1);else if(entry.length<3)entry+=key;notice='';document.getElementById('answer').textContent=entry||'?';document.getElementById('notice').textContent='';save();}});
document.getElementById('home').onclick=()=>{pause();screen='home';render();};
document.addEventListener('keydown',e=>{if(screen!=='play'||state.active?.phase!=='running')return;if(/^\d$/.test(e.key)){e.preventDefault();app.querySelector(`[data-action="key:${e.key}"]`)?.click();}else if(e.key==='Enter'){e.preventDefault();submit();}else if(e.key==='Backspace'){e.preventDefault();app.querySelector('[data-action="key:⌫"]')?.click();}});
document.addEventListener('visibilitychange',()=>{if(document.hidden){pause();stop();}else render();});window.addEventListener('pagehide',()=>{pause();save();stop();});render();
})();
