name: Deploy Website

on:
  push:
    branches:
      - main  # Or master, depending on your repository's default branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1' # Use a version compatible with your Gemfile
          bundler-cache: true # Runs 'bundle install' and caches gems

      - name: Build with Jekyll
        run: bundle exec jekyll build
        # Specify the _config.yml file if you need to
        # env:
        #   JEKYLL_CONFIG_FILE: _config.yml

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          # If you're deploying to a custom domain, add it here
          # cname: your.domain.com